export const fileTypeImgList = {
    "audio": "/images/file/audio.svg",
    "cad": "/images/file/cad.svg",
    "collect": "/images/file/collect.svg",
    "excel": "/images/file/excel.svg",
    "exe": "/images/file/exe.svg",
    "dir": "/images/file/folder.svg",
    "html": "/images/file/html.svg",
    "png": "/images/file/image.svg",
    "jpg": "/images/file/image.svg",
    "jpeg": "/images/file/image.svg",
    "gif": "/images/file/image.svg",
    "bmp": "/images/file/image.svg",
    "iso": "/images/file/iso.svg",
    "other": "/images/file/other.svg",
    "pdf": "/images/file/pdf.svg",
    "ppt": "/images/file/ppt.svg",
    "psd": "/images/file/psd.svg",
    "recycle": "/images/file/recycle.svg",
    "txt": "/images/file/txt.svg",
    "mp4": "/images/file/video.svg",
    "doc": "/images/file/word.svg",
    "zip": "/images/file/zip.svg",
    "rar": "/images/file/zip.svg",
    "7z": "/images/file/zip.svg"
}
